### ISSUE TITLE
M_PI not found

### ISSUE THREAD

**Issue by manuignatius** [org-arl/unet-contrib#14]
test_unet.c:68:38: error: ‘M_PI’ undeclared (first use in this function); did you mean ‘__P’?
     passbandsignal[i] = sin(f * (2 * M_PI) * (i / fs));

This is happening since '-lm' is not included in the Makefile

**Comment by notthetup** [comment]
Fixed in https://github.com/org-arl/unet-contrib/commit/3ee850524e30228f4b03fbbfb353b6923e7509a2
