### ISSUE TITLE
Make dataRate a property of Link Agents

### ISSUE THREAD

**Issue by shortstheory** [org-arl/unet-contrib#19]
Currently, the advertised bitrate of a given Link is only available by inspecting its underlying `phy`. For Links which do not have a `phy` (e.g. UdpLink), it is not possible to see what bitrate the Link advertises. Therefore, it would be good if the dataRate/bitrate of a given Link could be accessible as a Link parameter.

**Comment by mchitre** [comment]
Implemented in UnetStack3. Will be part of upcoming release.
