### ISSUE TITLE
About the running error of the example

### ISSUE THREAD

**Issue by Fendacola** [org-arl/unet-contrib#21]
When I run the simulation script (samples/ping/ping-sim.groovy) , I get an error. May I ask what is the reason?

![无标题](https://user-images.githubusercontent.com/50674464/57795260-15617480-7778-11e9-8e42-8a5ba0937084.jpg)

**Comment by Fendacola** [comment]
@Fendacola It's strange that I tried to run this example in version 1.4, but it worked well in version 1.3. I don't know why.

**Comment by Lucifish21** [comment]
@Fendacola It's strange that I try to run this example in version 1.4 and it will also report an error.
But it works well in version 1.3. I don't know why.

**Comment by mchitre** [comment]
I just downloaded version 1.4a and did a fresh install, and then ran the script. It works perfectly fine!
<img width="850" alt="image" src="https://user-images.githubusercontent.com/3949878/58752079-3d243c80-84db-11e9-879c-f21320221128.png">

**Comment by mchitre** [comment]
I suspect @Fendacola, your problem is that your root folder may not be set correctly. Do "File", "Set Root Folder", and ensure that the simulator 1.4 root folder is selected. If you previously used 1.3, the root folder may be set to that version.

**Comment by mchitre** [comment]
I'm guessing this is resolved, so closing it. @Fendacola @Lucifish21 please reopen if your issue persists.
