### ISSUE TITLE
RxFrameNtf is broken in unetpy

### ISSUE THREAD

**Issue by mchitre** [org-arl/unet-contrib#4]
`RxFrameNtf` seems to have two problems:
1. The data is not decoded correctly
2. When the data field is a list (as it should be), the string conversion of the message fails

For 1, we got:  
```
> ntf.data
{'clazz': '[B', 'data': 'AQID'}
```

For 2, we got:  
```
"unetpy/org_arl_unet_phy/__init__.py", line 97, in __str__
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by prasadtiru** [comment]
Fixed both the problems in commits 2ffc63af3d0b7de870473b06120bed3061c5e922 and org-arl/fjage@f765060eb61c1d7a8e32e13c311a8458628154d2 .
