### ISSUE TITLE
Backoff behavior not working?

### ISSUE THREAD

**Issue by eliasse** [org-arl/unet-contrib#52]
Hi,

I'm working with Unetstack in IntelliJ so I thought this problem might be related to that, but trying a 
simple script in the Unet IDE gives the same error. The simulation script below gives an MissingMethodException related to
the backoff() method. I'm running version 3.2.0 (communitu edition) of Unetstack on MacOS 10.14.6 (Mojave).
Am I doing anything wrong or is there a quick fix to the problem?

```
import org.arl.fjage.RealTimePlatform
import org.arl.fjage.BackoffBehavior
import org.arl.unet.UnetAgent
import org.arl.unet.*
import org.arl.fjage.*

platform = RealTimePlatform

class TinyAgent extends UnetAgent {
    void setup() {
        log.info("Hello world!")
    }
    void startup() {
        add new BackoffBehavior(5000, {
            println("backing off")
            backoff(5000)
        })
    }
}

simulate {
    node '1', address: 1, location: [0, 0, 0], shell: true, stack: { container ->
        container.add 'ta', new TinyAgent()
    }
}
```

**Comment by mchitre** [comment]
Try using a subclassed behavior, as Groovy may have trouble resolving the `backoff()` method from the closure:
```
add new BackoffBehavior(5000) {
  @Override
  void onExpiry() {
    println("backing off")
    backoff(5000)
  }
}
```

P.S. Of course, if you needed a constant 5 second tick, you may want to use a `TickerBehavior` instead. But I suspect you probably want to change the backoff duration dynamically.

**Comment by eliasse** [comment]
Cheers! I knew there'd be a workaround, only that I'm missing the Java/Groovy knowledge necessary :)
